# Generated by Django 5.2.3 on 2025-07-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rehabilitationcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RehabilitationCenter',
        ),
    ]
